### ISSUE TITLE
[RFC] Remove the pause feature for redeem

### ISSUE THREAD

**Issue by Mars12-dev** [nutsfinance/tapio-eth#26]
we have the pause feature for the different functions: mint , swap, redeem. I think we should remove the pause feature for the redeem functions to make it more safe for the user.

@zjb0807 What do you think ?

**Comment by zjb0807** [comment]
I don't think so. When the pool is injected, it is best to suspend all functions to reduce losses. There is no guarantee that redeem is safe

**Comment by Mars12-dev** [comment]
for the user how holds tapETHs , he should be able to redeem his tokens at any time, otherwise the protocol is not safe for the user.

**Comment by zjb0807** [comment]
Upgradeable contracts are also unsafe for users. We want to keep the protocol as secure as possible. If a hacker redeems the user's assets, it is not safe too.
